version: '3.7'

volumes:
  logs:
    driver: local
  db:

services:
  web:
    image: devbenatti/php7.4-composer
    working_dir: /var/www
    env_file:
      - .env
    dns: 8.8.8.8
    command: php -S 0.0.0.0:8080 -t public
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PHP_IDE_CONFIG: "serverName=xdebug-docker"
    expose:
      - 9000
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
    depends_on:
      - db
    links:
      - db
      - cache
  db:
    image: mysql:5.7
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: onepuchman
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: db
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
  cache:
    image: redis
    ports:
    - "6379:6379"
